export enum pagesNames {
    landingPage = '/',
    introPage = '/IntroPage',
    selectCasePage = '/SelectCasePage',
    rolesPresentationPage = '/RolesPresentationPage',
    teamsPresentationPage = '/TeamsPresentationPage',
    letsBeginPage = '/LetsBeginPage',
    gamePage = '/GamePage',
    intervenePage = '/IntervenePage',
    capturePage = '/CapturePage',
    veredictPage = '/VeredictPage',
    evidencePage = '/EvidencePage',
    testimoniesPage = '/TestimoniesPage',
    endGamePage = '/EndGamePage',
}